import type { Invoice } from './types';

export const mockInvoices: Invoice[] = [
  {
    id: '1',
    invoiceNumber: 'INV-001',
    payerName: 'Innovate Inc.',
    payerEmail: 'billing@innovate.com',
    amount: 2500,
    dueDate: '2024-08-15',
    issueDate: '2024-07-16',
    status: 'Funded',
    riskScore: 0.15,
    riskAssessment: 'Low risk. Payer has a consistent history of on-time payments and operates in a stable industry.',
  },
  {
    id: '2',
    invoiceNumber: 'INV-002',
    payerName: 'Quantum Solutions',
    payerEmail: 'accounts@quantum.com',
    amount: 5000,
    dueDate: '2024-09-01',
    issueDate: '2024-07-16',
    status: 'Pending',
    riskScore: 0.45,
    riskAssessment: 'Moderate risk. Payer is a relatively new company, and the industry is experiencing some volatility.',
  },
  {
    id: '3',
    invoiceNumber: 'INV-003',
    payerName: 'Apex Constructors',
    payerEmail: 'payables@apex.build',
    amount: 12000,
    dueDate: '2024-08-20',
    issueDate: '2024-07-01',
    status: 'Pending',
    riskScore: 0.2,
    riskAssessment: 'Low risk. Established company with a strong credit history. Large invoice amount is typical for their projects.',
  },
  {
    id: '4',
    invoiceNumber: 'INV-004',
    payerName: 'Synergy Labs',
    payerEmail: 'finance@synergylabs.io',
    amount: 1800,
    dueDate: '2024-08-10',
    issueDate: '2024-07-11',
    status: 'Paid',
    riskScore: 0.1,
    riskAssessment: 'Very low risk. Invoice has already been paid ahead of the due date.',
  },
  {
    id: '5',
    invoiceNumber: 'INV-005',
    payerName: 'Dynamic Digital',
    payerEmail: 'contact@dynamic.design',
    amount: 3200,
    dueDate: '2024-09-10',
    issueDate: '2024-07-12',
    status: 'Pending',
    riskScore: 0.65,
    riskAssessment: 'Medium-high risk. Payer has a history of late payments, and the invoice is for a non-essential service.',
  },
  {
    id: '6',
    invoiceNumber: 'INV-006',
    payerName: 'Healthful Goods',
    payerEmail: 'suppliers@healthful.com',
    amount: 750,
    dueDate: '2024-08-25',
    issueDate: '2024-07-15',
    status: 'Funded',
    riskScore: 0.12,
    riskAssessment: 'Low risk. Small amount and a reliable payer in the consumer goods sector.',
  },
];
